# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Runs all tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      #- run: npm run build --if-present
      - name: Install Dependencies
        run: yarn
      # - name: Run Unit Tests
      #   run: yarn test
      - name: Build app for deploy
        env:
          VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
          VITE_AUTHDOMAIN: ${{ secrets.VITE_AUTHDOMAIN }}
          VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
          VITE_STORAGEBUCKET: ${{ secrets.VITE_STORAGEBUCKET }}
          VITE_MESSAGINGSENDERID: ${{ secrets.VITE_MESSAGINGSENDERID }}
          VITE_APPID: ${{ secrets.VITE_APPID }}
          VITE_ITEMS_URL: ${{ secrets.VITE_ITEMS_URL }}
        run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
